#!/bin/sh
set -e

if [ "$1" = "triggered" ]; then
    echo "dbg:get triggered in shared-mime-info"
    if [ -x /usr/bin/update-mime-database ]; then
        update-mime-database /usr/share/mime
    fi
    exit 0
fi

echo "dbg:postinst in shared-mime-info"
if [ -x /usr/bin/update-mime-database ]; then
    update-mime-database /usr/share/mime
fi

#DEBHELPER#
